version: '3'

services:
  estategenius:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data/database:/app/data/database
      - ./data/uploaded_images:/app/uploaded_images
      - ./data/reports:/app/reports
      - ./data/logs:/app/logs
      - ./.env:/app/.env
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0